# Generated by Django 6.0.3 on 2026-03-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('stage', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
                ('date_range', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('objective', models.TextField()),
                ('details', models.JSONField(default=dict, help_text="{'Nginx': 'Web Server', 'Gunicorn': 'WSGI Server', 'Docker': 'Containerization', 'CI/CD': 'Continuous Integration/Deployment'}")),
                ('status', models.CharField(default='active', help_text='active, archived, etc.', max_length=50)),
            ],
        ),
    ]
