# Generated by Django 6.0.3 on 2026-03-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='details',
            field=models.JSONField(default=list, help_text="Список тегов, например ['Django', 'React']"),
        ),
    ]
