# Generated by Django 6.0.3 on 2026-03-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_experience_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(default='BASE_KERNEL', help_text='BASE_KERNEL, PATCH, CERTIFICATE', max_length=50)),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('date_range', models.CharField(max_length=50)),
                ('status', models.CharField(default='VERIFIED', max_length=50)),
            ],
        ),
    ]
