# Generated by Django 6.0.3 on 2026-03-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Краткое описание для превью')),
                ('content', models.TextField(help_text='Полный текст статьи (можно использовать Markdown/HTML)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.JSONField(default=list, help_text="Список тегов, например ['Linux', 'Proxmox']")),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
