# Generated by Django 6.0.3 on 2026-03-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_alias', models.CharField(max_length=150, verbose_name='Имя (Alias)')),
                ('return_node_ip', models.EmailField(max_length=254, verbose_name='Email отправителя')),
                ('encrypted_payload', models.TextField(verbose_name='Сообщение')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Входящее сообщение',
                'verbose_name_plural': 'Входящие сообщения',
                'ordering': ['-timestamp'],
            },
        ),
    ]
