# Generated by Django 6.0.3 on 2026-04-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(help_text='Полный текст статьи (можно использовать Markdown/HTML)', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_ru',
            field=models.TextField(help_text='Полный текст статьи (можно использовать Markdown/HTML)', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.TextField(help_text='Краткое описание для превью', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_ru',
            field=models.TextField(help_text='Краткое описание для превью', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='record_type_en',
            field=models.CharField(default='BASE_KERNEL', help_text='BASE_KERNEL, PATCH, CERTIFICATE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='record_type_ru',
            field=models.CharField(default='BASE_KERNEL', help_text='BASE_KERNEL, PATCH, CERTIFICATE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='objective_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='objective_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='stage_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='stage_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
