# Generated by Django 6.0.3 on 2026-06-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_blogpost_content_en_blogpost_content_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description. Если пусто — берётся excerpt. Рекомендуется 50–160 символов.', max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_en',
            field=models.CharField(blank=True, help_text='SEO meta description. Если пусто — берётся excerpt. Рекомендуется 50–160 символов.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_ru',
            field=models.CharField(blank=True, help_text='SEO meta description. Если пусто — берётся excerpt. Рекомендуется 50–160 символов.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO-заголовок (<title>). Если пусто — берётся title. Рекомендуется до 60 символов.', max_length=70),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='SEO-заголовок (<title>). Если пусто — берётся title. Рекомендуется до 60 символов.', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title_ru',
            field=models.CharField(blank=True, help_text='SEO-заголовок (<title>). Если пусто — берётся title. Рекомендуется до 60 символов.', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Картинка для соцсетей (Open Graph). Рекомендуется 1200×630.', upload_to='blog/og/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Полный текст статьи (Markdown)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(help_text='Полный текст статьи (Markdown)', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_ru',
            field=models.TextField(help_text='Полный текст статьи (Markdown)', null=True),
        ),
    ]
