# Generated by Django 6.0.3 on 2026-07-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_blogpost_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description. Если пусто — берётся excerpt. Рекомендуется 120–160 символов.', max_length=300),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description_en',
            field=models.CharField(blank=True, help_text='SEO meta description. Если пусто — берётся excerpt. Рекомендуется 120–160 символов.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description_ru',
            field=models.CharField(blank=True, help_text='SEO meta description. Если пусто — берётся excerpt. Рекомендуется 120–160 символов.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO-заголовок (<title>). Если пусто — берётся title. Рекомендуется до 60 символов, но можно до 100.', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='SEO-заголовок (<title>). Если пусто — берётся title. Рекомендуется до 60 символов, но можно до 100.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_title_ru',
            field=models.CharField(blank=True, help_text='SEO-заголовок (<title>). Если пусто — берётся title. Рекомендуется до 60 символов, но можно до 100.', max_length=100, null=True),
        ),
    ]
