# Generated by Django 6.0.3 on 2026-07-06 16:40

from django.db import migrations, models


def copy_stage_to_title(apps, schema_editor):
    """Копируем stage → title для записей, где title пустой или отличается
    от stage (на случай если должность хранилась в stage)."""
    Experience = apps.get_model('api', 'Experience')
    for exp in Experience.objects.all():
        changed = False
        # Основное поле
        if exp.stage and (not exp.title or exp.title != exp.stage):
            exp.title = exp.stage
            changed = True
        # Локализованные поля (ru/en)
        if hasattr(exp, 'stage_ru') and exp.stage_ru:
            if not exp.title_ru or exp.title_ru != exp.stage_ru:
                exp.title_ru = exp.stage_ru
                changed = True
        if hasattr(exp, 'stage_en') and exp.stage_en:
            if not exp.title_en or exp.title_en != exp.stage_en:
                exp.title_en = exp.stage_en
                changed = True
        if changed:
            exp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_extend_seo_field_lengths'),
    ]

    operations = [
        # Сначала копируем данные stage → title
        migrations.RunPython(copy_stage_to_title, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='experience',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='stage_en',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='stage_ru',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO-заголовок страницы (тег title). Если пусто — берётся title. Рекомендуется до 60 символов, но можно до 100.', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='SEO-заголовок страницы (тег title). Если пусто — берётся title. Рекомендуется до 60 символов, но можно до 100.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_title_ru',
            field=models.CharField(blank=True, help_text='SEO-заголовок страницы (тег title). Если пусто — берётся title. Рекомендуется до 60 символов, но можно до 100.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(help_text='Должность / роль (отображается как заголовок)', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title_en',
            field=models.CharField(help_text='Должность / роль (отображается как заголовок)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title_ru',
            field=models.CharField(help_text='Должность / роль (отображается как заголовок)', max_length=200, null=True),
        ),
    ]
