# Generated by Django 6.0.3 on 2026-07-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_experience_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Имя иконки из react-icons (например SiDocker, FaLinux, AiOutlineWindows, TbBrandUbuntu) — каталог: react-icons.github.io/react-icons. Для своих SVG: custom:имяфайла (файл в public/icons/skills/).', max_length=50),
        ),
    ]
