"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from dotenv import load_dotenv
# Load environment variables from .env file
load_dotenv()


from pathlib import Path

from core.env import require_env, get_bool

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Security-critical configuration read strictly from the environment (R4.1, R4.2,
# R5.1). require_env collects ALL missing/empty variables and raises MissingEnvError
# at settings-import time — before binding to a network port — listing every
# missing name (fail-fast).
_required = require_env('SECRET_KEY', 'ALLOWED_HOSTS', 'CORS_ALLOWED_ORIGINS')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _required['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
# Missing/empty DEBUG → off by default (R4.3).
DEBUG = get_bool("DEBUG", default=False)

ALLOWED_HOSTS = [h.strip() for h in _required['ALLOWED_HOSTS'].split(',') if h.strip()]

CORS_ALLOWED_ORIGINS = [
    o.strip() for o in _required['CORS_ALLOWED_ORIGINS'].split(',') if o.strip()
]

# CORS strictly by allow-list: cross-origin requests from origins not in the list
# receive no CORS headers (R4.6).
CORS_ALLOW_ALL_ORIGINS = False

# CSRF доверенные источники для работы админки за nginx (HTTPS-прокси).
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv(
        'CSRF_TRUSTED_ORIGINS', 'https://iamroot.pro,https://www.iamroot.pro'
    ).split(',')
    if o.strip()
]

# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'martor',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'portfolio'),
        'USER': os.getenv('USER_BD', 'kayal'),
        'PASSWORD': os.getenv('USER_PASSWORD_BD', 'bd#Tehn0l0gy'),
        'HOST': os.getenv('DB_HOST', 'db'),
        'PORT': os.getenv('PORT_BD', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

from django.utils.translation import gettext_lazy as _

LANGUAGES = (
    ('ru', _('Russian')),
    ('en', _('English')),
)

MODELTRANSLATION_DEFAULT_LANGUAGE = 'ru'
LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# [ SMTP YANDEX CONFIGURATION ]
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True  # Яндекс требует SSL на 465 порту
EMAIL_USE_TLS = False  # Если бы использовался порт 587, тогда нужно было бы включить TLS и отключить SSL

# Доступы берём только из окружения, без литеральных fallback (R5.1).
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')


# От кого будут приходить письма (Яндекс требует, чтобы это совпадало с EMAIL_HOST_USER)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
ADMIN_EMAIL = EMAIL_HOST_USER
# Куда будут приходить оповещения (тебе же на почту)
#ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', 'akaymanov@schooltech.ru')

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://127.0.0.1:3000')
# Только из окружения, без литерального fallback (R5.1). Пустое значение →
# Revalidation_Webhook отключается (R5.2); это не fail-fast.
REVALIDATION_SECRET = os.environ.get('REVALIDATION_SECRET', '')


USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# --- Production security hardening (R4.4) ---
# Применяется только при выключенном DEBUG, т.е. в продакшен-развёртывании.
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # SECURE_SSL_REDIRECT НЕ включаем: http→https редирект уже делает nginx
    # (return 301 на порту 80). Если включить здесь, Django редиректит на https
    # и внутренние SSR-запросы фронта (http://backend:8000, без заголовка
    # X-Forwarded-Proto) ломаются с "wrong version number" → таймауты ~30с.
    X_FRAME_OPTIONS = "DENY"  # XFrameOptionsMiddleware уже в MIDDLEWARE


# --- MARTOR (Markdown-редактор в админке) ---
MARTOR_THEME = 'bootstrap'
# Глобальные настройки редактора
MARTOR_ENABLE_CONFIGS = {
    'emoji': 'true',
    'imgur': 'false',       # загрузку картинок на imgur выключаем
    'mention': 'false',
    'jquery': 'true',
    'living': 'false',      # live-превью по запросу, не на каждый ввод
    'spellcheck': 'false',
    'hljs': 'true',         # подсветка кода в превью
}
# Кнопки тулбара
MARTOR_TOOLBAR_BUTTONS = [
    'bold', 'italic', 'horizontal', 'heading', 'pre-code', 'blockquote',
    'unordered-list', 'ordered-list', 'link', 'image-link', 'toggle-maximize',
]
# Markdown-расширения для серверного превью (включая блоки кода с подсветкой)
MARTOR_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.extra',
    'markdown.extensions.nl2br',
    'markdown.extensions.smarty',
    'markdown.extensions.fenced_code',
    'markdown.extensions.codehilite',
]
# Безопасность: какие теги/атрибуты разрешены при рендере превью (bleach).
MARTOR_ENABLE_LABEL = False
